# Generated by Django 5.0.1 on 2026-01-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_filename', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('estimate_date', models.DateField()),
                ('total_excl_tax', models.IntegerField(default=0)),
                ('total_incl_tax', models.IntegerField(default=0)),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('parsed_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parse History',
                'verbose_name_plural': 'Parse Histories',
                'db_table': 'parse_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_raw', models.CharField(max_length=255)),
                ('item_name_norm', models.CharField(max_length=100)),
                ('cost_type', models.CharField(choices=[('parts', 'Parts'), ('labor', 'Labor')], default='parts', max_length=20)),
                ('amount_excl_tax', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parse_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parser.parsehistory')),
            ],
            options={
                'db_table': 'parsed_items',
                'ordering': ['id'],
            },
        ),
    ]
